### PR TITLE
Fixing work of the WAIT_COMMAND environment variable

### PR DESCRIPTION
**Pull request by WagnerPMC**
# Reason for This PR
Issue #77 

# Description of Changes
See title

# License Acceptance
By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache license.

### CODE REVIEW

**Comment by WagnerPMC** [comment]
@ufoscout, Can you check my PR?

**Comment by ufoscout** [comment]
@WagnerPMC could you please fix the failing tests?

**Comment by WagnerPMC** [comment]
> @WagnerPMC could you please fix the failing tests?

Okay, I'll see what I can do.

**Comment by WagnerPMC** [comment]
@ufoscout I think we're ready to release it to the main

**Comment by ufoscout** [comment]
thank you!

**Review by ufoscout — APPROVED** [review]

**Pull request merged**
